version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    #devices:
      #- "/dev/video0:/dev/video0"
    environment:
      #- PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MONGO_URI=${MONGO_URI}

  frontend:
    build:
      context: ./rehab-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
